# Generated by Django 4.1.1 on 2022-09-29 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formation',
            old_name='formateur_id',
            new_name='formateur',
        ),
    ]
