# Generated by Django 4.1.1 on 2022-09-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_rename_formateur_id_formation_formateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscription',
            old_name='session_id',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='inscription',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='sessionformation',
            old_name='formation_id',
            new_name='formation',
        ),
    ]
