# Generated by Django 4.1.1 on 2022-09-30 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_rename_session_id_inscription_session_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formateur',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='formateur',
            name='lastname',
        ),
    ]
