# Generated by Django 4.1.1 on 2022-10-03 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formation', '0004_rename_firstname_formateur_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formateur',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lastname',
        ),
        migrations.AddField(
            model_name='formateur',
            name='matricule',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='formateur',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
