# Generated by Django 4.1.1 on 2022-10-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0005_remove_formateur_name_remove_student_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionformation',
            name='time',
            field=models.TimeField(default='10:00:00', verbose_name='time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessionformation',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
