# Generated by Django 4.1.1 on 2022-10-17 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0006_sessionformation_time_alter_sessionformation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionformation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sessionformation',
            name='time',
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 17, 9, 8, 55, 98907), verbose_name='date'),
        ),
    ]
